version: '3'

services:
  # Service PHP/Laravel
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - type: bind
        source: .
        target: /var/www/html
        consistency: cached
    depends_on:
      - db
    networks:
      - app-network

  # Serveur web Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: .
        target: /var/www/html
        consistency: cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Node.js pour Vue.js
  node:
    image: node:18-alpine
    container_name: vue-node
    working_dir: /var/www/html
    volumes:
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - type: bind
        source: .
        target: /var/www/html
        consistency: cached
    command: sh -c "npm install && npm run build"
    ports:
      - "5173:5173"
    networks:
      - app-network

# Volumes à conserver entre les redémarrages
volumes:
  dbdata:
  vendor:
  node_modules:

# Réseau interne
networks:
  app-network:
    driver: bridge
